### ISSUE TITLE
关于退票功能的一个问题

### ISSUE THREAD

**Issue by txtxj** [liuly0322/Flight-Server#1]
文档中对退票功能的要求为：

> 首先询问排第一的客户，若所退票能满足他的要求，则为他办理订票手续，否则依次询问其他排队候补的客户

但在 ```./code/ticket/Flight.cpp``` 中，函数 ```Flight::Refund``` 并没有在退票不能满足排第一的客户时，依次询问其他排队候补的客户。

对于每个航班的已订票、排队中 ```Order``` ，是否应当使用 ```List``` 而不是 ```Queue``` 更符合要求？

**Comment by liuly0322** [comment]
原文档要求使用 `queue` 实现候补队列的客户名单，附加要求提出的这一点功能在队列这一数据结构下无法（优雅）实现，所以并未实现。

改用 `List` 可以解决这一问题，~~但是不符合原文档要求，很神秘~~
